### ISSUE TITLE
Add support for native layouts

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/live_view_native#44]
After layouts are supported I believe we should change:

```
defmodule MyAppWeb.HelloLive do
  use Phoenix.LiveView
  use LiveViewNative.LiveView

```

we should instead add for the following to `MyWebApp`

```
  def live_view do
    quote do
      use Phoenix.LiveView,
        layout: {MyAppWeb.Layouts, :app}
      use LiveViewNative

      unquote(html_helpers())
      unquote(live_inspect())
    end
  end
```

This would add LVN to all LiveView modules. I like this as it reinforces the idea that all LiveViews could be native by just doing:

```
defmodule MyAppWeb.HelloLive do
   use MyWebApp, :live_view

```

and for existing LiveView apps that are adding Native it saves having to forget adding that `use LiveViewNative` to each module

**Comment by supernintendo** [comment]
@bcardarella Thanks! Did you have any thoughts for how layouts should work? The most common issue we're running into with modules that `use MyWebApp, :live_view` is that it applies the `:app` layout which includes HTML by default, breaking the native render. Some things I've considered:

1. We could expect app developers to override it manually via the `mount/3` callback in their own code. This already supported by `mount/3` ([link](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#c:mount/3)). Every LiveView in an application would have to have some code akin to the following:
```elixir
defmodule MyAppWeb.ExampleLive do
  use MyAppWeb, :live_view

  # ...

  @impl true
  def mount(_params, _session, socket) do
    case socket.assigns do
      %{platform: :web} ->
        {:ok, socket}

      _assigns ->
        {:ok, socket, layout: {MyAppWeb.LayoutView, :native}}
    end
  end

  # ...
end
```

The nice thing about this approach is that it's using upstream LiveView functionality and requires no custom abstractions on our end. It's also flexible in the way that it allows for platform-specific layouts (you could provide as many cases for platform, UI device idiom etc. as you need). The downside is that its asking app developers to do some extra work to handle non-web renders and shifts a lot of complexity to that `mount/3` callback.

2. We could use the first approach within the library but provide an abstraction around it to make dealing with layouts in multi-platform LVN apps easier. Some ideas include automatically assigning a layout based on the platform ID as part of the `on_mount` hook we're using to do platform-detection (which could then be overridden by the app developer). We could architect this so that non-web renders work out of the box even if you haven't provided a layout for a given platform, by falling back to an empty layout provided by the library.

3. We could ignore layouts entirely for non-web platforms. This seems like the least ideal approach but could make the most sense if we consider the responsibility of handling "layouts" to be that of the native client layer. When you think about a layout on an iOS app, you're usually thinking of a tab view at the bottom of the screen that lets you move between different views. It might provide the best and most responsive experience to have this be done natively in a way that doesn't require a round-trip to the server, with each tab being a separate `LiveView` that can maintain its own state. The downside to this approach is that it requires the app developer to drop into native Swift, Kotlin, etc. to define layouts for each platform.

**Comment by bcardarella** [comment]
I think the most correct thing is to have an alternative to the app layout. Basically we'd need our own render stack for template stitching. I can check with Phoenix core to see if any escape hatches on this exist or if we can get one

**Comment by supernintendo** [comment]
@bcardarella Why would we need that? I think the existing layout system works with LVN, we just need to tell people how to deal with multiple layouts in the same LiveView (or do it for them in the `on_mount` hook)?
