### ISSUE TITLE
Support Surface in addition to LiveView?

### ISSUE THREAD

**Issue by mayel** [liveview-native/live_view_native#49]
It mostly works already, see details at https://github.com/surface-ui/surface/issues/708

**Comment by AZholtkevych** [comment]
Rejecting according to @supernintendo

**Comment by supernintendo** [comment]
@mayel I like this idea and its cool to know that partial support for Surface with LiveView Native "just works" 🙂 The issue with external templates you pointed out is tricky to solve as both LVN and Surface have independent compilation steps and so the question of "who is responsible for compiling this external resource" becomes ambiguous (since neither library depends on the other).

Maintaining Surface compatibility isn't something we've discussed or have plans for (@bcardarella can correct me if I'm wrong). That said, my plan for https://github.com/liveview-native/live_view_native/issues/55 is that we can open up LVN's compilation macros for other libraries to hook into, which might allow for "bridge libraries" that provide integration between LVN and other component frameworks like Surface.

**Comment by bcardarella** [comment]
I haven't used Surface, am I understanding correctly that this would be for repurposing their LV components in the Native context?

**Comment by mayel** [comment]
@bcardarella no, at this stage it's not about LVN supporting any of Surface's features or components (though I would miss [contexts](https://surface-ui.org/contexts), Chris luckily recently talked about something similar coming to LV) 

This is simply being able to include `.swift` or `.jetpack` etc on top of `.sface` as [colocated templates in Surface views/components](https://surface-ui.org/components_basics#colocated-templates).

**Comment by mayel** [comment]
Having a similar macro to this in LVN would probably be enough to serve the purpose: https://hexdocs.pm/surface/Surface.html#embed_sface/1

**Comment by bcardarella** [comment]
But to support @supernintendo's position, I don't think we'd ever look to make support from our perspective specific for Surface. We instead should be compatible with *any* LV Component system so as long as Surface is produce LV components that could be the path forward

**Comment by mayel** [comment]
I noticed in the latest docs that using external templates is now more explicit: https://hexdocs.pm/live_view_native/0.2.0-beta.2/render-patterns.html#external-template-files

So FYI something like this works well to use Surface and LV side-by-side by just including `render_sface_or_native()` in a view/component (though I guess the first one with `:html` is not needed?):

```elixir
  defmacro render_sface_or_native do
    quote do 
      def render(%{format: :html} = assigns) do
        render_sface(assigns)
      end
      def render(%{format: _} = assigns) do
        render_native(assigns)
      end
      def render(assigns) do
        render_sface(assigns)
      end
    end
  end

**Comment by bcardarella** [comment]
@mayel now that https://github.com/phoenixframework/phoenix_live_view/pull/2823 is merged in the next version of LiveView well be abel to delegate to custom render functions, which for our purposes would be best used within isolated modules. This will allow more liberal use of systems like Surface and avoid any name collision on helpers and function components.
